name: Zyvexa Auto Profit
on:
  schedule:
    - cron: '0 * * * *' # Her saat başında otomatik çalışır (7/24)
  workflow_dispatch: # İstediğinde elinle de başlatabilirsin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install aiohttp
      - name: Run Profit Bot
        run: python money_maker.py
